"""
dialogue_generator.py
─────────────────────
Extracts structured dialogue lines from the storyboard scenes.

The storyboard already contains dialogue per scene (generated by
storyboard_generator). This module normalises those into a flat list
of {character, text, scene} dicts that voice_generator consumes.

It also generates a plain-text combined script for display.

Public API
----------
    extract_dialogues(scenes: list) -> dict
        {
          "script_text": str,           # markdown for display
          "lines": [                    # flat ordered list
            {
              "line_index": int,        # 1-based
              "scene_number": int,
              "character": str,
              "text": str,
            }
          ]
        }

    generate_dialogues(story, storyboard_display) -> str
        Legacy compatibility wrapper — returns markdown script.
"""

import re
from logger import log


def _parse_dialogue_block(raw: str, scene_number: int,
                          start_index: int) -> tuple[list, int]:
    """
    Parse a raw dialogue string like:
        "Pip:\\nHello world.\\n\\nBarnaby:\\nHi Pip."

    Returns (lines_list, next_start_index).
    """
    lines = []
    idx = start_index
    # Normalise escaped newlines
    raw = raw.replace("\\n", "\n")
    # Split into blocks separated by blank lines
    blocks = re.split(r"\n\s*\n", raw.strip())
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        # Expect "Character Name:\nDialogue text"
        match = re.match(r"^([^\n:]+):\s*\n(.+)", block, re.DOTALL)
        if match:
            char = match.group(1).strip()
            text = match.group(2).strip().replace("\n", " ")
            lines.append({
                "line_index": idx,
                "scene_number": scene_number,
                "character": char,
                "text": text,
            })
            idx += 1
        else:
            log.debug(f"Skipped unparseable dialogue block: {block[:60]}")
    return lines, idx


def extract_dialogues(scenes: list) -> dict:
    """
    Extract structured dialogue lines from storyboard scenes.

    Parameters
    ----------
    scenes : list of scene dicts from storyboard_generator

    Returns
    -------
    dict with "script_text" and "lines"
    """
    all_lines = []
    idx = 1

    for scene in scenes:
        n = scene.get("scene_number", 0)
        raw_dialogue = scene.get("dialogue", "")
        parsed, idx = _parse_dialogue_block(raw_dialogue, n, idx)
        all_lines.extend(parsed)

    # Build markdown display script
    script_lines = ["# 💬 Movie Script\n"]
    current_scene = None
    for line in all_lines:
        if line["scene_number"] != current_scene:
            current_scene = line["scene_number"]
            script_lines.append(f"\n---\n## 🎬 Scene {current_scene}\n")
        script_lines.append(f"**{line['character']}:**  \n{line['text']}\n")

    log.info(f"Extracted {len(all_lines)} dialogue lines across "
             f"{len(set(l['scene_number'] for l in all_lines))} scenes.")

    return {
        "script_text": "\n".join(script_lines),
        "lines": all_lines,
    }


# ── Legacy compatibility ──────────────────────────────────────────────────────

def generate_dialogues(story: str, storyboard_display: str = "") -> str:
    """
    Legacy wrapper used by old app.py.
    Returns the storyboard dialogue sections as plain markdown.
    """
    from gemini_client import ask
    prompt = f"""
You are a Pixar Animation Script Writer.
Read the storyboard and write natural character dialogues for every scene.

Return ONLY this format:
# 🎬 Scene N
Character Name:
Dialogue line here.

Rules:
• Short lines (1-2 sentences).
• No stage directions.
• Emotionally authentic.

Storyboard:
{storyboard_display}
"""
    return ask(prompt)
